AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TypeScript Clean Architecture Lambda Sample

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - stg
      - prod
    Description: Environment of his stack of resources

Resources:
  # Lambda
  Employees:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub EmployeesFunction-${Environment}
      CodeUri: ./build
      Handler: simple.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        List: # curl -X GET http://127.0.0.1:3000/employees
          Type: Api
          Properties:
            Path: /employees
            Method: get
        Get: # curl -X GET http://127.0.0.1:3000/employees/1
          Type: Api
          Properties:
            Path: /employees/{employeeId}
            Method: get
        Create: # curl -X POST http://127.0.0.1:3000/employees -d '{"message": "hogefuga"}'
          Type: Api
          Properties:
            Path: /employees
            Method: post
        Update: # curl -X PUT http://127.0.0.1:3000/employees/1
          Type: Api
          Properties:
            Path: /employees/{employeeId}
            Method: put
        Delete: # curl -X DELETE http://127.0.0.1:3000/employees/1
          Type: Api
          Properties:
            Path: /employees/{employeeId}
            Method: delete
  # Dynamo DB
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'DepartmentId'
          AttributeType: 'S'
        - AttributeName: 'EmployeeId'
          AttributeType: 'S'
        # KeySchemaに関係ない属性をここで宣言すると `Property AttributeDefinitions is inconsistent with the KeySchema of the table and the secondary indexes`
        # - AttributeName: 'Name'
        #   AttributeType: 'S'
        # - AttributeName: 'Email'
        #   AttributeType: 'S'
        # - AttributeName: 'CreatedAt'
        #   AttributeType: 'S'
        # - AttributeName: 'UpdatedAt'
        #   AttributeType: 'S'
      KeySchema:
        - AttributeName: 'DepartmentId'
          KeyType: 'HASH'
        - AttributeName: 'EmployeeId'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub Employees-${Environment}
